### ISSUE TITLE
Cannot Extract Data

### ISSUE THREAD

**Issue by JSirius21** [WaelHamze/xrm-ci-framework#233]
Hello,

Since the adding of the data part, we would like to use powershell scripts to export and extract data.
Exporting data is working good but not extracting : 
**ERROR : The term 'Expand-XrmCMData' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.**

This is my script which call the new scripts :

$scriptExportCMData =  $scriptPath + ".\Xrm.Framework.CI\ExportCMData.ps1" | Resolve-Path
Write-Verbose "scriptExportCMData: $scriptExportCMData"

& $scriptExportCMData \`
    -dataFile $dataFileDeduplicationRules \`
    -crmConnectionString $devConnectionString \`
    -crmConnectionTimeout $timeout \`
    -schemaFile $schemaFileDeduplicationRules \`
    -configurationMigrationModulePath $configurationMigrationModulePath \`
    -toolingConnectorModulePath $toolingConnectorModulePackagePath
 
$scriptExtractCMData = $scriptPath + ".\Xrm.Framework.CI\ExtractCMData.ps1" | Resolve-Path
Write-Verbose "scriptExtractCMData: $scriptExtractCMData"

& $scriptExtractCMData \`
	-dataFile $dataFileDeduplicationRules \`
	-extractFolder $extractFolderDeduplicationRules \`
	-sortExtractedData $False \`
	-splitExtractedData $True

**Comment by WaelHamze** [comment]
@JSirius21 if you were using the packages from nuget/ps gallery, I have just released a new version containing these new cmdlets

**Comment by JSirius21** [comment]
@WaelHamze thank you for your quick support, but the last commit don't fix this issue
https://github.com/WaelHamze/xrm-ci-framework/commit/f421e1d6934100cde6129c2d44e45e0dc538e475
Mayby I don't take the good project (MSDYNV9\Xrm.Framework.CI)?

**Comment by JSirius21** [comment]
Sorry I didn't notice that you were talking about Powershell Gallery.
I downloaded the 9.0.0.41 version and I still have the same behavior...

**Comment by JSirius21** [comment]
@WaelHamze I'm sorry, I didn't copy the good version into my application. It's working well ith the version 9.0.0.41!
